version: 2
formats:
  - htmlzip
# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  dependencies:
    pre:
      - pip install sphinx sphinx_rtd_theme

  script:
    - sphinx-build -b html docs/source docs/build/html

python:
  install:
    - requirements: docs/requirements.txt
